# Use root/example as user/password credentials
version: '3.1'

services:

  nodebackend:
    build: ./
    ports:
      - "4200:4200"
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    environment:
      - NODE_ENV=development
      - CI=true
